[workspace]
resolver="2"
members = [
    "core",
    "apps/cli",
    "apps/desktop/src-tauri", "engines/minimax", "engines/mcts", "crates/attack-tables",
]

[workspace.package]
license = "MIT"
edition = "2021"
repository = "https://github.com/TheBlackSquidward/diesel"


