[workspace]
resolver="2"
members = [
    "core",
    "crates/*",
    "apps/cli",
    "apps/desktop/src-tauri",
]

[workspace.package]
license = "MIT"
edition = "2021"
repository = "https://github.com/TheBlackSquidward/diesel"


