[workspace]
resolver="2"
members = [
    "diesel-core",
    "crates/diesel-gen",
    "apps/diesel-cli", "apps/diesel-desktop/src-tauri",
    "engines/minimax", "engines/mcts",
]

[workspace.package]
license = "MIT"
edition = "2021"
repository = "https://github.com/TheBlackSquidward/diesel"


